language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_fd04893a5d6f_key -iv $encrypted_fd04893a5d6f_iv
  -in ansible/secrets.tar.enc -out ansible/secrets.tar -d
- tar xvf ansible/secrets.tar
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt update
- sudo apt install ansible
after_success:
- ansible/deploy.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - node_modules
