language: java
jdk:
  - oraclejdk8
sudo: required
dist: trusty
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_fd04893a5d6f_key -iv $encrypted_fd04893a5d6f_iv -in ansible/inventories/production/group_vars/all.yml.enc -out ansible/inventories/production/group_vars/all.yml -d
  - openssl aes-256-cbc -K $encrypted_fd04893a5d6f_key -iv $encrypted_fd04893a5d6f_iv -in ansible/ssh/id_rsa.enc -out ansible/ssh/id_rsa -d
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt update
  - sudo apt install ansible
#install:
# - curl -sSL https://github.com/rancher/cli/releases/download/v0.6.4/rancher-linux-amd64-v0.6.4.tar.gz | tar -xzp --strip-components=2
after_success:
  - ansible/deploy.sh
#  - pwd
#  - ls -l build/
#  - ls -l build/libs
#  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#  - export REPO=leward/splatoon
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
#  - echo $REPO:$TRAVIS_COMMIT
#  - echo $TAG
#  - echo "docker build -t $REPO:$TRAVIS_COMMIT ."
#  - docker build -t $REPO:$TRAVIS_COMMIT .
#  - echo "docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG"
#  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
#  - echo "docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER"
#  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
#  - echo "docker push $REPO:$TAG"
#  - docker push $REPO:$TAG
#  - echo "docker push $REPO:travis-$TRAVIS_BUILD_NUMBER"
#  - docker push $REPO:travis-$TRAVIS_BUILD_NUMBER
#  - docker run --rm -it -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY -e CATTLE_URL=$CATTLE_URL etlweather/gaucho upgrade $CATTLE_SERVICE_ID --start_first=True --complete_previous --auto_complete
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 - node_modules